#pragma once
// Combat vehicle cockpit shells (Grape, Negling, Caliban): the driver's
// compartment fitted inside each real hull. The data is generated by
// research/cockpit/combat_shells.py, which also checks that every point of
// each shell lies inside the vehicle's own mesh.
#include "cockpit.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <vector>
namespace edf6vr {
#include "cockpit_combat_shells.inc"
inline const CombatShell* FindCombatShell(CockpitKind kind) noexcept {
    for(const auto& s:kCombatShells)if(s.kind==kind)return &s;
    return nullptr;
}
inline bool IsCombatKind(CockpitKind kind) noexcept {return FindCombatShell(kind)!=nullptr;}
// Each model's paint round the cut, measured from its own albedo by
// research/cockpit/combat_paint.py (sRGB; no game texture is shipped): the
// hull's colour, and a second tone for trim (the Caliban's red, the camouflage's
// other colour). The lid and the cockpit's painted surfaces take it, so the
// covers pass for the body. A variant's model carries the base model's bone
// too, so the variants come first.
struct CombatPaint {CockpitKind kind;const wchar_t* model;unsigned char paint[3],accent[3];};
inline constexpr CombatPaint kCombatPaints[]={
    {CockpitKind::CombatNegling,L"Vehicle402_Rocket_edf6benefits",{130,126,98},{178,171,107}},   // desert camouflage
    {CockpitKind::CombatNegling,L"Vehicle402_Rocket",{51,55,56},{80,87,88}},                       // grey camouflage
    {CockpitKind::CombatGrape,L"Vehicle401_STRIKER",{51,55,48},{70,76,66}},                        // olive grey
    {CockpitKind::CombatCaliban,L"v507_rescuetank_happy",{3,50,122},{152,0,0}},                  // blue
    {CockpitKind::CombatCaliban,L"v507_rescuetank",{170,170,171},{154,42,42}},                   // white, red trim
};
inline float CombatPaintLinear(unsigned char c) noexcept {
    const float s=c/255.f;return s<=.04045f?s/12.92f:std::pow((s+.055f)/1.055f,2.4f);
}
// The shell in cabin coordinates: the cabin origin is the eye less the seated
// eye offset, and cabin +X is model -X (the pilot's right).
struct CombatCabinShell {
    unsigned planeCount=0;float n[8][3]{},d[8]{};bool pane[8]{};
    float sill=0,floor=0,sponson=0;
    float xLeft=0,xInner=0,xRight=0,zRear=0,zFront=0;   // xLeft < xInner <= xRight
};
inline CombatCabinShell CombatCabin(const CombatShell& s) noexcept {
    CombatCabinShell c{};
    const float o[3]={s.eye[0],s.eye[1]-kCockpitSeatedEye[1],s.eye[2]-kCockpitSeatedEye[2]};
    c.planeCount=s.planeCount;
    for(unsigned i=0;i<s.planeCount&&i<8;++i) {
        const auto& p=s.planes[i];
        c.n[i][0]=-p.n[0];c.n[i][1]=p.n[1];c.n[i][2]=p.n[2];
        c.d[i]=p.d-(p.n[0]*o[0]+p.n[1]*o[1]+p.n[2]*o[2]);
        c.pane[i]=p.pane;
    }
    c.sill=s.sill-o[1];c.floor=s.floor-o[1];c.sponson=s.sponson-o[1];
    c.xLeft=-(s.xOuter-o[0]);c.xInner=-(s.xInner-o[0]);c.xRight=-(s.xRight-o[0]);
    c.zRear=s.zRear-o[2];c.zFront=s.zFront-o[2];
    return c;
}
// The cut (the user's round 3, like the Titan's covered turret well): the
// hull above the cut's floor, from cutRear forward, goes, so the rider sees
// ahead, to both sides and up over the vehicle's own body. The game keeps
// drawing the rest of the hull; a triangle that meets the cut is left out of
// its draw, and the lid (CombatLid) draws what of it lies outside the cut and
// covers the cut itself, so the body's inside is never seen. Model coordinates.
using CombatPoint=std::array<float,3>;
using CombatPolygon=std::vector<CombatPoint>;
// Convex: inside where n.p<=d for every plane.
struct CombatRegion {unsigned count=0;float n[16][3]{};float d[16]{};};
inline float CombatDot(const float* n,const CombatPoint& p) noexcept {return n[0]*p[0]+n[1]*p[1]+n[2]*p[2];}
// The part of a convex polygon where n.p<=d.
inline CombatPolygon CombatClipBelow(const CombatPolygon& poly,const float* n,float d) {
    CombatPolygon out;
    for(std::size_t i=0;i<poly.size();++i) {
        const auto& a=poly[i];const auto& b=poly[(i+1)%poly.size()];
        const float da=CombatDot(n,a)-d,db=CombatDot(n,b)-d;
        if(da<=1e-6f)out.push_back(a);
        if((da<-1e-6f&&db>1e-6f)||(da>1e-6f&&db<-1e-6f)) {
            const float t=da/(da-db);out.push_back({a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t,a[2]+(b[2]-a[2])*t});
        }
    }
    return out;
}
// The cut, `inset` into it: above cutFloor (the sill, or the Caliban's window
// frames), ahead of cutRear - up to cutTop there and no wider than
// cutHalfWidth behind cutWideFrom, and at any height from cutTopRear on. What
// stands above cutTop behind cutTopRear is kept (the Caliban's visor under its
// red lights, with the roof and the light block), and so are the sides behind
// cutWideFrom (its tall body's walls and the pillars carrying the visor down).
// One region when there is neither a cap nor a width limit.
inline bool CombatCutCapped(const CombatShell& s) noexcept {return s.cutTop<90;}
inline bool CombatCutNarrow(const CombatShell& s) noexcept {return s.cutHalfWidth<90;}
inline std::vector<CombatRegion> CombatCutRegions(const CombatShell& s,float inset=0) {
    std::vector<CombatRegion> out;
    auto region=[&](float from,bool capped,bool narrow) {
        CombatRegion r{};
        auto add=[&](float x,float y,float z,float d){r.n[r.count][0]=x;r.n[r.count][1]=y;r.n[r.count][2]=z;r.d[r.count]=d-inset;++r.count;};
        add(0,-1,0,-s.cutFloor);add(0,0,-1,-from);
        if(capped)add(0,1,0,s.cutTop);
        if(narrow){add(1,0,0,s.cutHalfWidth);add(-1,0,0,s.cutHalfWidth);}
        out.push_back(r);
    };
    region(s.cutRear,CombatCutCapped(s),CombatCutNarrow(s));
    if(CombatCutNarrow(s))region(s.cutWideFrom,CombatCutCapped(s),false);
    if(CombatCutCapped(s))region(s.cutTopRear,false,false);
    return out;
}
// The cut's floor (the deck's height), and its half width at z.
inline float CombatCutFloor(const CombatShell& s,float) noexcept {return s.cutFloor;}
inline float CombatCutHalfWidth(const CombatShell& s,float z) noexcept {
    return CombatCutNarrow(s)&&z<s.cutWideFrom?s.cutHalfWidth:1e9f;
}
// Does a triangle (nine floats) reach more than 1 mm into the cut? Those the
// game no longer draws; the lid draws the rest of them.
inline bool CombatCutMeets(const CombatShell& s,const float* t) {
    for(const auto& r:CombatCutRegions(s,.001f)) {
        CombatPolygon poly{{t[0],t[1],t[2]},{t[3],t[4],t[5]},{t[6],t[7],t[8]}};
        for(unsigned k=0;k<r.count&&poly.size()>=3;++k)poly=CombatClipBelow(poly,r.n[k],r.d[k]);
        if(poly.size()>=3)return true;
    }
    return false;
}
// Across the hull on the line {y, z}: its outer skin's two sides, the
// outermost crossings (nothing inside the hull matters). False if fewer than
// two triangles cross the line.
inline bool CombatHullSpan(const std::vector<float>& hull,const std::vector<unsigned>& candidates,float y,float z,float& right,float& left) {
    right=1e9f;left=-1e9f;unsigned crossings=0;
    for(const auto t:candidates) {
        const float* a=&hull[t];const float* b=&hull[t+3];const float* c=&hull[t+6];
        const float d=(b[1]-a[1])*(c[2]-a[2])-(c[1]-a[1])*(b[2]-a[2]);
        if(std::fabs(d)<1e-10f)continue;
        const float u=((y-a[1])*(c[2]-a[2])-(c[1]-a[1])*(z-a[2]))/d,w=((b[1]-a[1])*(z-a[2])-(y-a[1])*(b[2]-a[2]))/d;
        if(u<0||w<0||u+w>1)continue;
        const float x=a[0]+u*(b[0]-a[0])+w*(c[0]-a[0]);
        right=std::min(right,x);left=std::max(left,x);++crossings;
    }
    return crossings>=2&&left-right>.02f;
}
// The first hull face over (x, z) above `from`: what a fitting standing there
// must stay under to be inside the vehicle's body. 1e9 if nothing is above.
inline float CombatHullAbove(const std::vector<float>& hull,float x,float z,float from) {
    float lowest=1e9f;
    for(std::size_t i=0;i+9<=hull.size();i+=9) {
        const float* a=&hull[i];const float* b=a+3;const float* c=a+6;
        const float d=(b[0]-a[0])*(c[2]-a[2])-(c[0]-a[0])*(b[2]-a[2]);
        if(std::fabs(d)<1e-10f)continue;
        const float u=((x-a[0])*(c[2]-a[2])-(c[0]-a[0])*(z-a[2]))/d,w=((b[0]-a[0])*(z-a[2])-(x-a[0])*(b[2]-a[2]))/d;
        if(u<0||w<0||u+w>1)continue;
        const float y=a[1]+u*(b[1]-a[1])+w*(c[1]-a[1]);
        if(y>from)lowest=std::min(lowest,y);
    }
    return lowest;
}
// The parts of a convex polygon outside every region.
inline void CombatCutWindows(const CombatPolygon& poly,const std::vector<CombatRegion>& regions,std::size_t first,std::vector<CombatPolygon>& out) {
    if(poly.size()<3)return;
    if(first>=regions.size()){out.push_back(poly);return;}
    const auto& r=regions[first];CombatPolygon rest=poly;
    for(unsigned k=0;k<r.count&&rest.size()>=3;++k) {
        const float flipped[3]={-r.n[k][0],-r.n[k][1],-r.n[k][2]};
        CombatCutWindows(CombatClipBelow(rest,flipped,-r.d[k]),regions,first+1,out);   // outside this plane
        rest=CombatClipBelow(rest,r.n[k],r.d[k]);
    }
}
}
